name: Build resume PDF and publish HTML+PDF to docx

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Cache Puppeteer Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            puppeteer-${{ runner.os }}-

      - name: Install deps
        run: npm ci

      - name: Generate PDF
        run: node resume-to-pdf.js

      - name: Verify PDF exists
        run: |
          test -f Divyansh_Rana_Resume.pdf || (echo "PDF not generated" && exit 1)
          ls -lah Divyansh_Rana_Resume.pdf

      - name: Prepare publish folder
        run: |
          mkdir -p publish
          # Copy your existing resume.html and rename it to index.html
          cp resume.html publish/index.html
          # Inject a "Download PDF" link right before </body>
          sed -i '/<\/body>/i <p><a href="Divyansh_Rana_Resume.pdf" download>Download PDF</a></p>' publish/index.html
          # Copy the generated PDF
          cp Divyansh_Rana_Resume.pdf publish/
          echo "Publish folder contents:"
          ls -lah publish

      - name: Push to docx:main
        env:
          DOCX_PUSH_TOKEN: ${{ secrets.DOCX_PUSH_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail
          git config --global init.defaultBranch main

          cd publish
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Publish resume HTML+PDF from ${GITHUB_SHA} [skip ci]"
          git branch -M main

          git remote add origin "https://divyanshrana:${DOCX_PUSH_TOKEN}@github.com/divyanshrana/docx.git"
          git remote -v | sed -E 's/:([^@]+)@/:***HIDDEN***@/'

          git push --force origin main