name: Build PDF and publish to docx (stable only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Cache Puppeteer Chromium
        uses: actions/cache@v4
        with:
          path: ~/.cache/puppeteer
          key: puppeteer-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            puppeteer-${{ runner.os }}-

      - name: Install deps
        run: npm ci

      - name: Generate PDF (stable filename)
        run: node resume-to-pdf.js

      - name: Verify PDF exists
        run: |
          test -f Divyansh_Rana_Resume.pdf || (echo "PDF not generated" && exit 1)
          ls -lah Divyansh_Rana_Resume.pdf

      # Publish ONLY the PDF to docx:main
      - name: Push to docx:main (stable only)
        env:
          DOCX_PUSH_TOKEN: ${{ secrets.DOCX_PUSH_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          set -euo pipefail
          git config --global init.defaultBranch main

          # Make a clean temp repo containing ONLY the PDF
          mkdir -p publish && cp Divyansh_Rana_Resume.pdf publish/
          cd publish
          git init
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Divyansh_Rana_Resume.pdf
          git commit -m "Publish stable resume PDF from ${GITHUB_SHA} [skip ci]"
          git branch -M main

          # Use username:TOKEN format for reliability
          git remote add origin "https://divyanshrana:${DOCX_PUSH_TOKEN}@github.com/divyanshrana/docx.git"
          git remote -v | sed -E 's/:([^@]+)@/:***HIDDEN***@/'

          # Overwrite docx:main with ONLY this file
          git push --force origin main